name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 700 keyfile
          ssh -t -i keyfile ubuntu@ec2-13-234-240-1.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
